# Generated by Django 6.0.2 on 2026-02-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Detailed description of the notice.')),
                ('priority', models.CharField(choices=[('High', 'High Priority'), ('Medium', 'Medium Priority'), ('Low', 'Low Priority')], default='Medium', max_length=10)),
                ('external_link', models.URLField(blank=True, help_text='Link to a PDF, Google Form, or external site.', null=True)),
                ('embed_code', models.TextField(blank=True, help_text='Paste the full iframe embed code here (e.g., from YouTube or Google Forms).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
