# Generated by Django 6.0.2 on 2026-02-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_club_type_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_type',
            field=models.CharField(choices=[('tech', 'Technical & Coding'), ('cultural', 'Curricular & Cultural'), ('sports', 'Sports & Fitness'), ('media', 'Media & Communication')], default='tech', max_length=20),
        ),
    ]
